using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using NLog;

namespace MapleShark2.Tools {
    /// <summary>
    /// Compatibility manifest: measured per-edge evidence of which build's decoder script may be used as
    /// a fallback for which (build, opcode, direction). Generated by the harness sweep and classified by
    /// Harness/analysis/manifest.py; only rows with state == accept are loaded here.
    ///
    /// Evidence is bound to script content, not build numbers: every accepted edge carries the hash of
    /// the opcode script (script_sha) and of the importable-module surface it ran with (env_sha). An
    /// edge whose hashes no longer match the files on disk is stale and is never used — re-run the
    /// sweep + classifier after editing scripts.
    /// </summary>
    public class ScriptManifest {
        private static readonly Logger logger = LogManager.GetCurrentClassLogger();

        public const string FileName = "manifest.csv";

        // The manifest is measured on locale-0 captures only; never applied to other locales.
        private const byte ManifestLocale = 0;

        private sealed class Edge {
            public uint SourceBuild;
            public string ScriptSha;
            public string EnvSha;
            public int QualityRank; // USEFUL=0, PARTIAL=1, STUB=2
            public double CleanFraction;
        }

        private readonly Dictionary<(uint Target, ushort Opcode, bool Outbound), List<Edge>> edges =
            new Dictionary<(uint, ushort, bool), List<Edge>>();
        private readonly Dictionary<uint, string> envHashCache = new Dictionary<uint, string>();

        public ScriptManifest() {
            string path = Path.Combine(Helpers.GetScriptsRoot(), FileName);
            if (!File.Exists(path)) {
                logger.Info("No script manifest at {0}; fallback decoding disabled.", path);
                return;
            }

            try {
                Load(path);
                logger.Info("Script manifest: {0} accepted edges for {1} (build, opcode, direction) targets.",
                    edges.Values.Sum(l => l.Count), edges.Count);
            } catch (Exception ex) {
                edges.Clear();
                logger.Error(ex, "Failed to load script manifest {0}; fallback decoding disabled.", path);
            }
        }

        /// <summary>
        /// Find the best accepted, hash-valid fallback source for a packet whose own build has no script.
        /// Candidates are tried best-first (quality tier, then measured clean fraction, then newer build).
        /// </summary>
        public bool TryResolve(byte locale, uint version, bool outbound, ushort opcode, out uint sourceBuild) {
            sourceBuild = 0;
            if (locale != ManifestLocale) return false;
            if (!edges.TryGetValue((version, opcode, outbound), out List<Edge> candidates)) return false;

            foreach (Edge edge in candidates) {
                string scriptPath = Helpers.GetScriptPath(locale, edge.SourceBuild, outbound, opcode);
                if (!File.Exists(scriptPath)) continue;
                if (FileSha(scriptPath) != edge.ScriptSha) {
                    logger.Warn("Manifest edge {0}->{1} 0x{2:X4}: script changed since measurement; skipping.",
                        edge.SourceBuild, version, opcode);
                    continue;
                }

                if (EnvSha(edge.SourceBuild) != edge.EnvSha) {
                    logger.Warn("Manifest edge {0}->{1} 0x{2:X4}: module surface changed since measurement; skipping.",
                        edge.SourceBuild, version, opcode);
                    continue;
                }

                sourceBuild = edge.SourceBuild;
                return true;
            }

            return false;
        }

        private void Load(string path) {
            using var reader = new StreamReader(path);
            string[] header = SplitCsv(reader.ReadLine() ?? "");
            Dictionary<string, int> col = header.Select((name, i) => (name, i)).ToDictionary(t => t.name, t => t.i);

            string line;
            while ((line = reader.ReadLine()) != null) {
                if (line.Length == 0) continue;
                string[] f = SplitCsv(line);
                if (f[col["state"]] != "accept") continue;

                ushort opcode = Convert.ToUInt16(f[col["opcode"]].Substring(2), 16);
                var key = (uint.Parse(f[col["target_build"]]), opcode, f[col["direction"]] == "OUT");
                long n = long.Parse(f[col["n"]]);
                var edge = new Edge {
                    SourceBuild = uint.Parse(f[col["source_build"]]),
                    ScriptSha = f[col["script_sha"]],
                    EnvSha = f[col["env_sha"]],
                    QualityRank = f[col["quality"]] switch { "USEFUL" => 0, "PARTIAL" => 1, _ => 2 },
                    CleanFraction = n == 0 ? 0 : (double) long.Parse(f[col["ok_exact"]]) / n,
                };

                if (!edges.TryGetValue(key, out List<Edge> list)) {
                    edges[key] = list = new List<Edge>();
                }

                list.Add(edge);
            }

            foreach (List<Edge> list in edges.Values) {
                list.Sort((a, b) => {
                    int cmp = a.QualityRank.CompareTo(b.QualityRank);
                    if (cmp != 0) return cmp;
                    cmp = b.CleanFraction.CompareTo(a.CleanFraction);
                    return cmp != 0 ? cmp : b.SourceBuild.CompareTo(a.SourceBuild);
                });
            }
        }

        // Minimal RFC-4180 field splitter; manifest fields may be quoted by python's csv writer.
        private static string[] SplitCsv(string line) {
            var fields = new List<string>();
            var sb = new StringBuilder();
            bool quoted = false;
            for (int i = 0; i < line.Length; i++) {
                char c = line[i];
                if (quoted) {
                    if (c == '"' && i + 1 < line.Length && line[i + 1] == '"') {
                        sb.Append('"');
                        i++;
                    } else if (c == '"') {
                        quoted = false;
                    } else {
                        sb.Append(c);
                    }
                } else if (c == '"') {
                    quoted = true;
                } else if (c == ',') {
                    fields.Add(sb.ToString());
                    sb.Clear();
                } else {
                    sb.Append(c);
                }
            }

            fields.Add(sb.ToString());
            return fields.ToArray();
        }

        /// <summary>SHA-256 (first 12 hex chars, lowercase) of one file — must mirror Harness ScriptHost.FileSha.</summary>
        private static string FileSha(string path) {
            using var sha = SHA256.Create();
            return Convert.ToHexString(sha.ComputeHash(File.ReadAllBytes(path))).Substring(0, 12).ToLowerInvariant();
        }

        /// <summary>
        /// Importable-module-surface hash — must mirror Harness ScriptHost.EnvHash exactly: a leading
        /// byte for the sys.path order (1 = version folder first, which is what both the harness sweep
        /// and this application now use), then name + content of every top-level .py of the scripts root
        /// and the build's version folder, ordered by file name.
        /// </summary>
        private string EnvSha(uint build) {
            if (envHashCache.TryGetValue(build, out string cached)) return cached;
            using IncrementalHash sha = IncrementalHash.CreateHash(HashAlgorithmName.SHA256);
            sha.AppendData(new byte[] { 1 });
            foreach (string dir in new[] { Helpers.GetScriptsRoot(), Helpers.GetScriptFolder(ManifestLocale, build) }) {
                if (!Directory.Exists(dir)) continue;
                foreach (string file in Directory.GetFiles(dir, "*.py")
                             .OrderBy(Path.GetFileName, StringComparer.OrdinalIgnoreCase)) {
                    sha.AppendData(Encoding.UTF8.GetBytes(Path.GetFileName(file)));
                    sha.AppendData(File.ReadAllBytes(file));
                }
            }

            string hash = Convert.ToHexString(sha.GetHashAndReset()).Substring(0, 12).ToLowerInvariant();
            envHashCache[build] = hash;
            return hash;
        }
    }
}
