''' ServerEnter '''
# Auto-generated (Phase 4a/4b) from ServerEnterPacket: Request
from script_api import *

add_int("fieldPlayer.ObjectId")
add_long("player.Character.Id")
add_short("player.Character.Channel")
add_long("player.Character.Exp")
add_long("player.Character.RestExp")
add_long("player.Currency.Meso")
add_long("player.Currency.Meret")
add_long("Unknown")
add_long("player.Currency.GameMeret")
add_long("Unknown")
add_long("Unknown")
add_long("player.Currency.ValorToken")
add_long("player.Currency.Treva")
add_long("player.Currency.Rue")
add_long("player.Currency.HaviFruit")
add_long("player.Currency.ReverseCoin")
add_long("player.Currency.MentorToken")
add_long("player.Currency.MenteeToken")
add_long("player.Currency.StarPoint")
add_long("player.Currency.MesoToken")
add_unicode_str("player.Character.Picture")
add_byte("fieldPlayer.PvpDuelRankQueueState")
add_byte("fieldPlayer.SurvivalQueueState")
count = add_short("player.Unlock.Maps.Count")
for i0 in range(count):
    add_int("mapId")
count = add_short("player.Unlock.Taxis.Count")
for i0 in range(count):
    add_int("mapId")
add_long("player.Character.GuildId")
add_unicode_str("player.Character.GuildName")
add_unicode_str("Target.BrowserMainUrl.ToString()")
add_unicode_str("$'{Target.WebUri.Scheme}://{Target.WebUri.Author")
add_unicode_str("$'^https?://{Regex.Escape(Target.WebUri.Host)}(:")
add_unicode_str("Unknown")
