''' MeretMarket '''
# Auto-generated (Phase 4a/4b) from MeretMarketPacket: Error, LoadPersonalListings, LoadSales, ListItem, RemoveListing, RelistItem, UpdateProduct, UpdateProfit, UpdateExpiration, LoadDesigners, AddDesigner, LoadDesignerItems, RemoveDesigner, LoadItems, LoadBlueprints, Purchase, FeaturedPremium, FeaturedUgc, LoadUgcItems
from script_api import *

mode = add_byte("mode")
if mode == 0:  # Error
    add_byte("category")
    add_int("error")
    add_int("marketId")
    add_long("productId")
    add_long("Unknown")
    add_bool("isPremium")
elif mode == 11:  # LoadPersonalListings
    add_long("Unknown")
    count = add_int("items.Count")
    for i0 in range(count):
        add_bool("true")
        add_bool("true")
        add_int("Unknown")
        add_long("Id")
        add_int("Unknown")
        add_long("Id")
        add_byte("Status")
        add_int("ItemMetadata.Id")
        add_int("TabId")
        add_byte("ItemMetadata.Limit.Gender.FilterFlag()")
        add_int("Unknown")
        add_long("Price")
        add_int("Unknown")
        add_int("Unknown")
        add_int("SalesCount")
        add_int("Unknown")
        add_long("CreationTime")
        add_long("CreationTime")
        add_long("ListingEndTime")
        add_int("Unknown")
        add_long("PromotionEndTime")
        add_long("Unknown")
        add_long("CreationTime")
        add_int("Unknown")
        add_long("SellerAccountId")
        add_long("SellerCharacterId")
        add_unicode_str("Unknown")
        add_unicode_str("SellerCharacterName")
        add_unicode_str("string.Join(',', string.Join(',', Tags) + ', ' +")
        add_unicode_str("Description")
        add_unicode_str("SellerCharacterName")
        add_long("Id")
        add_unicode_str("Id.ToString()")
        add_unicode_str("Name")
        add_byte("1")
        add_int("1")
        add_long("AccountId")
        add_long("CharacterId")
        add_unicode_str("Author")
        add_long("CreationTime")
        add_unicode_str("Url")
        add_byte("Unknown")
        add_long("Uid")
        add_int("Length")
        add_int("Instrument")
        add_unicode_str("Author")
        add_unicode_str("Title")
        add_str("Mml")
        add_int("Unknown")
        add_long("AuthorAccountId")
        add_long("CreationTime")
        add_unicode_str("FileName")
        add_long("BlueprintUid")
        add_int("Length")
        add_int("Width")
        add_int("Height")
        add_long("CreationTime.ToUnixTimeSeconds()")
        add_int("Type")
        add_long("AccountId")
        add_long("CharacterId")
        add_unicode_str("CharacterName")
        add_byte("Category")
elif mode == 12:  # LoadSales
    count = add_int("items.Count")
    for i0 in range(count):
        add_long("Id")
        add_long("Unknown")
        add_unicode_str("Name")
        add_int("Unknown")
        add_int("Unknown")
        add_long("Unknown")
        add_long("Unknown")
        add_unicode_str("Unknown")
        add_unicode_str("Unknown")
        add_int("Unknown")
        add_long("Price")
        add_long("SoldTime")
        add_long("Profit")
elif mode == 13:  # ListItem
    # --- layout truncated: pWriter.WriteMarketItem (opaque write) (no wire-safe continuation) ---
    pass
elif mode == 14:  # RemoveListing
    add_int("Unknown")
    add_long("id")
    add_long("id")
elif mode == 18:  # RelistItem
    add_bool("true")
    add_int("Unknown")
    add_long("Id")
    add_int("Unknown")
    add_long("Id")
    add_byte("Status")
    add_int("ItemMetadata.Id")
    add_int("TabId")
    add_byte("ItemMetadata.Limit.Gender.FilterFlag()")
    add_int("Unknown")
    add_long("Price")
    add_int("Unknown")
    add_int("Unknown")
    add_int("SalesCount")
    add_int("Unknown")
    add_long("CreationTime")
    add_long("CreationTime")
    add_long("ListingEndTime")
    add_int("Unknown")
    add_long("PromotionEndTime")
    add_long("Unknown")
    add_long("CreationTime")
    add_int("Unknown")
    add_long("SellerAccountId")
    add_long("SellerCharacterId")
    add_unicode_str("Unknown")
    add_unicode_str("SellerCharacterName")
    add_unicode_str("string.Join(',', string.Join(',', Tags) + ', ' +")
    add_unicode_str("Description")
    add_unicode_str("SellerCharacterName")
    add_long("Id")
    add_unicode_str("Id.ToString()")
    add_unicode_str("Name")
    add_byte("1")
    add_int("1")
    add_long("AccountId")
    add_long("CharacterId")
    add_unicode_str("Author")
    add_long("CreationTime")
    add_unicode_str("Url")
    add_byte("Unknown")
    add_long("Uid")
    add_int("Length")
    add_int("Instrument")
    add_unicode_str("Author")
    add_unicode_str("Title")
    add_str("Mml")
    add_int("Unknown")
    add_long("AuthorAccountId")
    add_long("CreationTime")
    add_unicode_str("FileName")
    add_long("BlueprintUid")
    add_int("Length")
    add_int("Width")
    add_int("Height")
    add_long("CreationTime.ToUnixTimeSeconds()")
    add_int("Type")
    add_long("AccountId")
    add_long("CharacterId")
    add_unicode_str("CharacterName")
    add_byte("Category")
elif mode == 19:  # UpdateProduct
    add_bool("true")
    add_int("Unknown")
    add_long("Id")
    add_int("Unknown")
    add_long("Id")
    add_byte("Status")
    add_int("ItemMetadata.Id")
    add_int("TabId")
    add_byte("ItemMetadata.Limit.Gender.FilterFlag()")
    add_int("Unknown")
    add_long("Price")
    add_int("Unknown")
    add_int("Unknown")
    add_int("SalesCount")
    add_int("Unknown")
    add_long("CreationTime")
    add_long("CreationTime")
    add_long("ListingEndTime")
    add_int("Unknown")
    add_long("PromotionEndTime")
    add_long("Unknown")
    add_long("CreationTime")
    add_int("Unknown")
    add_long("SellerAccountId")
    add_long("SellerCharacterId")
    add_unicode_str("Unknown")
    add_unicode_str("SellerCharacterName")
    add_unicode_str("string.Join(',', string.Join(',', Tags) + ', ' +")
    add_unicode_str("Description")
    add_unicode_str("SellerCharacterName")
    add_long("Id")
    add_unicode_str("Id.ToString()")
    add_unicode_str("Name")
    add_byte("1")
    add_int("1")
    add_long("AccountId")
    add_long("CharacterId")
    add_unicode_str("Author")
    add_long("CreationTime")
    add_unicode_str("Url")
    add_byte("Unknown")
    add_long("Uid")
    add_int("Length")
    add_int("Instrument")
    add_unicode_str("Author")
    add_unicode_str("Title")
    add_str("Mml")
    add_int("Unknown")
    add_long("AuthorAccountId")
    add_long("CreationTime")
    add_unicode_str("FileName")
    add_long("BlueprintUid")
    add_int("Length")
    add_int("Width")
    add_int("Height")
    add_long("CreationTime.ToUnixTimeSeconds()")
    add_int("Type")
    add_long("AccountId")
    add_long("CharacterId")
    add_unicode_str("CharacterName")
    add_byte("Category")
elif mode == 21:  # UpdateExpiration
    add_int("Unknown")
    add_long("item.Id")
    add_long("item.Id")
    add_byte("item.Status")
    add_byte("Unknown")
    add_long("item.ListingEndTime")
elif mode == 22:  # LoadDesigners
    count = add_byte("designers.Count")
    for i0 in range(count):
        add_long("designer.AccountId")
        add_long("designer.CharacterId")
        add_unicode_str("designer.Name")
        add_unicode_str("designer.Picture")
elif mode == 23:  # AddDesigner
    add_long("playerInfo.AccountId")
    add_long("playerInfo.CharacterId")
    add_unicode_str("playerInfo.Name")
    add_unicode_str("playerInfo.Picture")
    add_int("items.Count")
    # --- layout truncated: loop body has control flow / unknown write (no wire-safe continuation) ---
elif mode == 24:  # RemoveDesigner
    add_long("characterId")
elif mode == 25:  # LoadDesignerItems
    add_long("playerInfo.AccountId")
    add_long("playerInfo.CharacterId")
    add_unicode_str("playerInfo.Name")
    add_unicode_str("playerInfo.Picture")
    add_int("items.Count")
    # --- layout truncated: loop body has control flow / unknown write (no wire-safe continuation) ---
elif mode == 26:  # UpdateProfit
    add_long("saleId")
    add_long("saleId")
elif mode == 27:  # LoadItems
    add_int("marketItems.Count")
    add_int("totalItems")
    add_int("startPage")
    # --- layout truncated: loop body has control flow / unknown write (no wire-safe continuation) ---
elif mode == 28:  # LoadBlueprints
    add_int("marketItems.Count")
    add_int("totalItems")
    add_byte("itemsPerPage")
    add_int("startPage")
    # --- layout truncated: loop body has control flow / unknown write (no wire-safe continuation) ---
elif mode == 30:  # Purchase
    add_byte("totalQuantity")
    add_int("premiumMarketId")
    add_long("ugcMarketItemId")
    add_int("Unknown")
    add_int("Unknown")
    add_long("Unknown")
    add_int("itemIndex")
    add_int("totalQuantity")
    add_int("Unknown")
    add_byte("Unknown")
    add_unicode_str("Unknown")
    add_unicode_str("Unknown")
    add_long("price")
    add_byte("Unknown")
    add_byte("Unknown")
    add_int("Unknown")
    add_int("Unknown")
    add_int("Unknown")
    add_int("Unknown")
elif mode == 101:  # FeaturedPremium
    add_byte("section")
    add_byte("tabId")
    add_byte("Unknown")
    add_byte("marketSlots")
    # --- layout truncated: loop body has control flow / unknown write (no wire-safe continuation) ---
elif mode == 102:  # FeaturedUgc
    add_int("promoItems.Count + newItems.Count")
    # --- layout truncated: loop body has control flow / unknown write (no wire-safe continuation) ---
elif mode == 103:  # LoadUgcItems
    add_byte("(promoItems.Count + newItems.Count)")
    # --- layout truncated: loop body has control flow / unknown write (no wire-safe continuation) ---
