''' Wedding '''
# Auto-generated (Phase 4a/4b) from WeddingPacket: UpdateMarriage, UpdateHall, Error, Proposal, Engaged, DivorceRequest, Reserve, ConfirmReservation, RequestCancelReservation, DeclinedCancelReservation, AcceptCancelReservation, ChangeReservationRequest, AcceptReservationChange, ClearHallEntries, SideTalk, RemoveHallListEntry, SearchUser, SendInvite, WeddingSetup, WeddingStep, WeddingEmote
from script_api import *

mode = add_byte("mode")
if mode == 0:  # UpdateMarriage
    add_long("Id")
    add_byte("Status")
    add_long("CreationTime")
    add_long("Unknown")
    add_long("CharacterId")
    add_long("AccountId")
    add_unicode_str("Name")
    add_bool("!IsOnline")
    add_long("CharacterId")
    add_long("AccountId")
    add_unicode_str("Name")
    add_bool("!IsOnline")
    add_long("Exp")
    add_unicode_str("Partner1.Message")
    add_unicode_str("Partner2.Message")
    add_unicode_str("Unknown")
    add_unicode_str("Profile")
    count = add_int("ExpHistory.Count")
    for i0 in range(count):
        add_short("exp.Type")
        add_long("exp.Amount")
        add_long("exp.Time")
elif mode == 1:  # UpdateHall
    add_long("Id")
    add_int("PackageId")
    add_int("PackageHallId")
    add_long("CeremonyTime")
    add_bool("Public")
    add_long("ReserverAccountId")
    add_long("ReserverCharacterId")
    add_unicode_str("ReserverName")
    add_unicode_str("PartnerName")
    add_long("Unknown")
    add_long("Unknown")
    add_long("Unknown")
    add_long("Unknown")
    add_long("Unknown")
    add_int("GuestList.Count")
    add_int("Unknown")
elif mode == 2:  # Error
    add_byte("error")
elif mode == 3:  # Proposal
    add_long("characterId")
    add_unicode_str("name")
elif mode == 6:  # Engaged
    add_long("Id")
    add_byte("Status")
    add_long("CreationTime")
    add_long("Unknown")
    add_long("CharacterId")
    add_long("AccountId")
    add_unicode_str("Name")
    add_bool("!IsOnline")
    add_long("CharacterId")
    add_long("AccountId")
    add_unicode_str("Name")
    add_bool("!IsOnline")
    add_long("Exp")
    add_unicode_str("Partner1.Message")
    add_unicode_str("Partner2.Message")
    add_unicode_str("Unknown")
    add_unicode_str("Profile")
    count = add_int("ExpHistory.Count")
    for i0 in range(count):
        add_short("exp.Type")
        add_long("exp.Amount")
        add_long("exp.Time")
elif mode == 8:  # DivorceRequest
    pass
elif mode == 13:  # Reserve
    add_long("Id")
    add_int("PackageId")
    add_int("PackageHallId")
    add_long("CeremonyTime")
    add_bool("Public")
    add_long("ReserverAccountId")
    add_long("ReserverCharacterId")
    add_unicode_str("ReserverName")
    add_unicode_str("PartnerName")
    add_long("Unknown")
    add_long("Unknown")
    add_long("Unknown")
    add_long("Unknown")
    add_long("Unknown")
    add_int("GuestList.Count")
elif mode == 15:  # ConfirmReservation
    add_long("Id")
    add_int("PackageId")
    add_int("PackageHallId")
    add_long("CeremonyTime")
    add_bool("Public")
    add_long("ReserverAccountId")
    add_long("ReserverCharacterId")
    add_unicode_str("ReserverName")
    add_unicode_str("PartnerName")
    add_long("Unknown")
    add_long("Unknown")
    add_long("Unknown")
    add_long("Unknown")
    add_long("Unknown")
    add_int("GuestList.Count")
elif mode == 16:  # RequestCancelReservation
    pass
elif mode == 17:  # DeclinedCancelReservation
    add_short("reply")
elif mode == 19:  # AcceptCancelReservation
    pass
elif mode == 20:  # ChangeReservationRequest
    add_long("Id")
    add_int("PackageId")
    add_int("PackageHallId")
    add_long("CeremonyTime")
    add_bool("Public")
    add_long("ReserverAccountId")
    add_long("ReserverCharacterId")
    add_unicode_str("ReserverName")
    add_unicode_str("PartnerName")
    add_long("Unknown")
    add_long("Unknown")
    add_long("Unknown")
    add_long("Unknown")
    add_long("Unknown")
    add_int("GuestList.Count")
    add_long("differenceCost")
elif mode == 22:  # AcceptReservationChange
    add_long("Id")
    add_int("PackageId")
    add_int("PackageHallId")
    add_long("CeremonyTime")
    add_bool("Public")
    add_long("ReserverAccountId")
    add_long("ReserverCharacterId")
    add_unicode_str("ReserverName")
    add_unicode_str("PartnerName")
    add_long("Unknown")
    add_long("Unknown")
    add_long("Unknown")
    add_long("Unknown")
    add_long("Unknown")
    add_int("GuestList.Count")
    add_long("differenceCost")
elif mode == 23:  # ClearHallEntries
    pass
elif mode == 24:  # SideTalk
    add_long("hall.MarriageId")
    add_long("Id")
    add_int("PackageId")
    add_int("PackageHallId")
    add_long("CeremonyTime")
    add_bool("Public")
    add_long("ReserverAccountId")
    add_long("ReserverCharacterId")
    add_unicode_str("ReserverName")
    add_unicode_str("PartnerName")
    add_long("Unknown")
    add_long("Unknown")
    add_long("Unknown")
    add_long("Unknown")
    add_long("Unknown")
    add_int("GuestList.Count")
elif mode == 25:  # RemoveHallListEntry
    add_long("hall.Id")
elif mode == 27:  # SearchUser
    add_long("AccountId")
    add_long("CharacterId")
    add_unicode_str("Name ?? string.Empty")
elif mode == 29:  # SendInvite
    pass
elif mode == 30:  # WeddingSetup
    add_int("agreeType")
    # --- layout truncated: if (no wire-safe continuation) ---
elif mode == 31:  # WeddingStep
    add_byte("step")
elif mode == 39:  # WeddingEmote
    add_byte("value")
    # --- layout truncated: if (no wire-safe continuation) ---
